### ISSUE TITLE
Broadcom WiFi

### ISSUE THREAD

**Issue by buttery-potato** [getsolus/doflicky#2]
after installing broadcom wifi drivers I still had to run "sudo depmod" before reboot in order for wifi to work

**Comment by JoshStrobl** [comment]
It is expected that you reboot after installing drivers so they get loaded. Our usysconf will automatically run depmod already: https://github.com/getsolus/usysconf/blob/legacy/src/handlers/kernel/depmod.c

**Comment by buttery-potato** [comment]
even after reboot I had to run sudo depmod
